name: minefind
version: 1.0.0
main: rpg.Main
description: minefind plugin by sciencemj

commands:
  minestart:
    description: start
    usage: /minestart
  minestop:
    description: stop
    usage: /minestop